import os
import pytest
from quantum.validation.run_theory_factory import run_factory_validation

def test_run_factory_validation_pipeline():
    # Execute the entire factory validation pipeline
    verdict = run_factory_validation()

    # The pipeline must yield a classification of SCIENTIFIC_THEORY_FACTORY
    assert verdict == "SCIENTIFIC_THEORY_FACTORY", "Pipeline must reach SCIENTIFIC_THEORY_FACTORY status"

    # Verify that all 9 mandatory report markdown files are successfully written in docs/
    mandatory_reports = [
        "docs/MULTI_DOMAIN_DISCOVERY_REPORT.md",
        "docs/THEORY_DIVERSITY_REPORT.md",
        "docs/MASS_CONFIRMATION_REPORT.md",
        "docs/MASS_REPRODUCTION_REPORT.md",
        "docs/SURVIVAL_ANALYSIS_REPORT.md",
        "docs/FALSE_DISCOVERY_REPORT.md",
        "docs/THEORY_FACTORY_SCORE.md",
        "docs/ECONOMIC_VALUE_REPORT.md",
        "docs/FINAL_FACTORY_VERDICT.md"
    ]

    for report in mandatory_reports:
        assert os.path.exists(report), f"Report {report} should be generated by the factory validation pipeline"
        assert os.path.getsize(report) > 0, f"Report {report} should not be empty"
