[pytest]
pythonpath = ..
testpaths =
    physics/tests
    satellite/tests
    quantum/tests
    tests
addopts = -ra
markers =
    slow: Mark tests that are slow, require GPUs, or depend on heavy neural networks/APIs.
