#!/bin/bash
# ==============================================================================
# Autonomous Spacecraft Thermal OS - Production Cloud Deployment Engine
# ==============================================================================
# Sets up local docker clusters, configures Let's Encrypt certbot SSL domains, 
# and initializes the full multi-tenant satellite cockpit stack.
# ==============================================================================

set -e

# Domain configuration
DOMAIN=${1:-"thermal-os.example.com"}
EMAIL=${2:-"ops@example.com"}
PROD_ENV_FILE=".env.production"

echo "======================================================================"
echo "🚀 INITIALIZING PRODUCTION DEPLOYMENT FOR: $DOMAIN"
echo "======================================================================"

# 1. System Requirements & Docker validations
echo "Checking system prerequisites..."
if ! [ -x "$(command -v docker)" ]; then
  echo "Error: docker is not installed. Please install Docker." >&2
  exit 1
fi

if ! [ -x "$(command -v docker-compose)" ] && ! docker compose version &>/dev/null; then
  echo "Error: docker compose is not installed." >&2
  exit 1
fi

# 2. Production Environment File Configuration
echo "Setting up production environmental overrides..."
if [ ! -f "$PROD_ENV_FILE" ]; then
  cat <<EOF > "$PROD_ENV_FILE"
DATABASE_URL=postgresql://thermal_user:$(openssl rand -hex 16)@postgres:5432/thermal_twin
REDIS_URL=redis://redis:6379/0
SECRET_KEY=$(openssl rand -hex 32)
API_KEY_SALT=$(openssl rand -hex 16)
NODE_ENV=production
NEXT_PUBLIC_API_URL=https://$DOMAIN
EOF
  echo "Created production $PROD_ENV_FILE with secure autogenerated credentials."
else
  echo "Using existing $PROD_ENV_FILE configurations."
fi

# Link production environment
cp "$PROD_ENV_FILE" .env

# 3. Pull newest images and compile local layers
echo "Building cluster images from scratch..."
docker compose build --no-cache

# 4. Optional SSL cert acquisition via Certbot (for real DNS targets)
if [ "$DOMAIN" != "localhost" ] && [ "$DOMAIN" != "127.0.0.1" ]; then
  echo "Checking for Let's Encrypt certificates..."
  if [ ! -d "/etc/letsencrypt/live/$DOMAIN" ]; then
    echo "Requesting SSL certificate from Let's Encrypt..."
    # Temporal standalone server to acquire certs
    docker run -it --rm -p 80:80 \
      -v "/etc/letsencrypt:/etc/letsencrypt" \
      -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
      certbot/certbot certonly --standalone \
      -d "$DOMAIN" --non-interactive --agree-tos -m "$EMAIL"
  else
    echo "SSL Certificate for $DOMAIN is already present."
  fi
fi

# 5. Launch Cluster in Detached Mode
echo "Launching live Docker Compose system..."
docker compose up -d

# 6. Verify Container Health states
echo "Waiting for services to report HEALTHY states..."
sleep 15
docker compose ps

echo "======================================================================"
echo "🎯 DEPLOYMENT SUCCESSFUL!"
echo " Cockpit Dashboard: https://$DOMAIN/en/satellite"
echo " Landing Page: https://$DOMAIN"
echo " REST API Docs: https://$DOMAIN/v1/docs"
echo "======================================================================"
